FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
COPY py-src ./py-src
COPY pyproject.toml .

RUN pip install --upgrade pip && \
    pip install -e .

EXPOSE 5000

CMD ["python", "-m", "flask", "run", "--host=0.0.0.0"]
