FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
COPY py-src ./py-src

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "-m", "flask", "run", "--host=0.0.0.0"]
